# Generated by Django 5.2.10 on 2026-01-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الأستاذ")),
                (
                    "academic_title",
                    models.CharField(
                        choices=[
                            ("أستاذ", "أستاذ"),
                            ("أستاذ_مساعد", "أستاذ مساعد"),
                            ("مدرس", "مدرس"),
                            ("مدرس_مساعد", "مدرس مساعد"),
                            ("معيد", "معيد"),
                        ],
                        default="مدرس",
                        max_length=50,
                        verbose_name="اللقب العلمي",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, verbose_name="التخصص"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="core.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "أستاذ",
                "verbose_name_plural": "الأساتذة",
                "ordering": ["department", "name"],
                "indexes": [
                    models.Index(
                        fields=["department"], name="instructors_departm_6ee5ec_idx"
                    ),
                    models.Index(
                        fields=["academic_title"], name="instructors_academi_7baed6_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="instructors_is_acti_a5a7f7_idx"
                    ),
                ],
            },
        ),
    ]
