# Generated by Django 5.2.10 on 2026-01-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="is_maintenance_mode",
            field=models.BooleanField(default=False, verbose_name="وضع الصيانة"),
        ),
    ]
