# Generated by Django 5.2.10 on 2026-01-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المادة")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رمز المادة"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("الأولى", "المرحلة الأولى"),
                            ("الثانية", "المرحلة الثانية"),
                            ("الثالثة", "المرحلة الثالثة"),
                            ("الرابعة", "المرحلة الرابعة"),
                            ("الخامسة", "المرحلة الخامسة"),
                        ],
                        default="الأولى",
                        max_length=20,
                        verbose_name="المرحلة",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=3, verbose_name="ساعات أسبوعية"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="core.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد الدراسية",
                "ordering": ["department", "stage", "name"],
                "indexes": [
                    models.Index(
                        fields=["department"], name="subjects_su_departm_1115a0_idx"
                    ),
                    models.Index(fields=["stage"], name="subjects_su_stage_1c7721_idx"),
                    models.Index(
                        fields=["is_active"], name="subjects_su_is_acti_51f8be_idx"
                    ),
                ],
            },
        ),
    ]
