# Generated by Django 5.2.9 on 2026-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="اسم المادة"
            ),
        ),
    ]
