# Generated by Django 5.2.10 on 2026-01-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم العطلة")),
                ("date", models.DateField(verbose_name="التاريخ")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "recurring",
                    models.BooleanField(default=False, verbose_name="سنوية متكررة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "عطلة",
                "verbose_name_plural": "العطل الرسمية",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="calendar_ap_date_ca79e4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DepartmentOffDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("السبت", "السبت"),
                            ("الأحد", "الأحد"),
                            ("الإثنين", "الإثنين"),
                            ("الثلاثاء", "الثلاثاء"),
                            ("الأربعاء", "الأربعاء"),
                            ("الخميس", "الخميس"),
                            ("الجمعة", "الجمعة"),
                        ],
                        max_length=20,
                        verbose_name="اليوم",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="off_days",
                        to="core.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "يوم راحة",
                "verbose_name_plural": "أيام الراحة",
                "ordering": ["department", "day"],
                "unique_together": {("department", "day")},
            },
        ),
    ]
