# Generated by Django 5.2.10 on 2026-01-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القاعة")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("قاعة", "قاعة دراسية"),
                            ("مختبر_حاسوب", "مختبر حاسوب"),
                            ("مختبر_علمي", "مختبر علمي"),
                            ("قاعة_مؤتمرات", "قاعة مؤتمرات"),
                            ("مكتبة", "مكتبة"),
                        ],
                        default="قاعة",
                        max_length=50,
                        verbose_name="نوع القاعة",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="السعة"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=50, verbose_name="الطابق"),
                ),
                (
                    "has_projector",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على بروجكتر"
                    ),
                ),
                (
                    "has_computers",
                    models.BooleanField(default=False, verbose_name="يحتوي على حاسبات"),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(default=True, verbose_name="يحتوي على سبورة"),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(default=False, verbose_name="يحتوي على تكييف"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="core.department",
                        verbose_name="القسم",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعة",
                "verbose_name_plural": "القاعات",
                "ordering": ["department", "name"],
                "indexes": [
                    models.Index(
                        fields=["department"], name="rooms_room_departm_4e5a86_idx"
                    ),
                    models.Index(
                        fields=["room_type"], name="rooms_room_room_ty_632e38_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="rooms_room_is_acti_2e361c_idx"
                    ),
                ],
            },
        ),
    ]
