# Generated by Django 5.2.10 on 2026-01-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instructors", "0001_initial"),
        ("rooms", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("السبت", "السبت"),
                            ("الأحد", "الأحد"),
                            ("الإثنين", "الإثنين"),
                            ("الثلاثاء", "الثلاثاء"),
                            ("الأربعاء", "الأربعاء"),
                            ("الخميس", "الخميس"),
                        ],
                        max_length=20,
                        verbose_name="اليوم",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="وقت البداية")),
                ("end_time", models.TimeField(verbose_name="وقت النهاية")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("محاضرة", "محاضرة"),
                            ("مختبر", "مختبر"),
                            ("امتحان", "امتحان"),
                            ("اجتماع", "اجتماع"),
                            ("أخرى", "أخرى"),
                        ],
                        default="محاضرة",
                        max_length=20,
                        verbose_name="نوع الحصة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="instructors.instructor",
                        verbose_name="الأستاذ",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="rooms.room",
                        verbose_name="القاعة",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="subjects.subject",
                        verbose_name="المادة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
                "ordering": ["day", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["room", "day"], name="schedules_s_room_id_89e73c_idx"
                    ),
                    models.Index(
                        fields=["instructor", "day"],
                        name="schedules_s_instruc_a7b243_idx",
                    ),
                    models.Index(
                        fields=["day", "start_time", "end_time"],
                        name="schedules_s_day_8a6d04_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="schedules_s_is_acti_ae1f3d_idx"
                    ),
                ],
            },
        ),
    ]
